import type { CatalogData } from "./types";

export const demoData: CatalogData = {
  source: "demo",
  apps: [
    {
      id: "app-secret-manager",
      name: "Secret Manager",
      repository: "https://github.com/karukimori-wq/Secret-Manager",
      service: "Vercel / Google Sheets / Google Drive",
      productionUrl: "https://secret-manager-xvor.vercel.app",
      previewUrl: "https://secret-manager-xvor-q6xifijz7-junichi-t-j11-s-projects.vercel.app",
      description: "Secret、Repository、Deployment、設定画面へのリンクをまとめる台帳アプリ。",
    },
    {
      id: "app-external-intelligence-system",
      name: "External Intelligence System",
      repository: "https://github.com/karukimori-wq/External-Intelligence-System",
      service: "Vercel / Supabase",
      productionUrl: "https://external-intelligence-system-1rtht1iff-junichi-t-j11-s-projects.vercel.app",
      previewUrl: "",
      description: "開発中の知識、進捗、判断材料を集約し、次の開発で再利用するための外部知能。",
    },
    {
      id: "app-growth-engine",
      name: "Growth Engine",
      repository: "https://github.com/karukimori-wq/Growth-Engine",
      service: "Vercel / Supabase",
      productionUrl: "https://growth-engine-ruby-nine.vercel.app",
      previewUrl: "",
      description: "集客、予約、販売導線を管理し、ビジネス側の成長施策を動かすアプリ。",
    },
    {
      id: "app-velvet",
      name: "Velvet",
      repository: "https://github.com/karukimori-wq/Velvet",
      service: "Cloudflare Workers / D1",
      productionUrl: "https://velvet.karukimori.workers.dev",
      previewUrl: "",
      description: "占い師や専門家の記憶、顧客理解、接客文脈を扱うプロフェッショナル支援アプリ。",
    },
    {
      id: "app-numeria-studio",
      name: "Numeria Studio",
      repository: "https://github.com/karukimori-wq/numeria-studio",
      service: "Cloudflare Workers / D1 / ChatGPT Sites",
      productionUrl: "https://numeria-studio.illusionddt.chatgpt.site",
      previewUrl: "",
      description: "数秘鑑定セッションとレポート作成を行う鑑定スタジオ。",
    },
    {
      id: "app-sns-planner",
      name: "SNS Planner",
      repository: "https://github.com/karukimori-wq/SNS-planner",
      service: "ChatGPT Sites / GitHub",
      productionUrl: "https://sns-planner.illusionddt.chatgpt.site",
      previewUrl: "",
      description: "SNS投稿、ハッシュタグ、リール、ストーリー案を作成し、投稿計画を整理するアプリ。",
    },
    {
      id: "app-communication-planner",
      name: "Communication Planner",
      repository: "https://github.com/karukimori-wq/Communication-Planner",
      service: "Cloudflare / GitHub",
      productionUrl: "",
      previewUrl: "",
      description: "1対1の会話、返信案、安全確認を管理し、別人への誤送信や文脈混同を防ぐアプリ。",
    },
    {
      id: "app-ai-platform-core",
      name: "AI Platform Core",
      repository: "https://github.com/karukimori-wq/ai-platform-core",
      service: "Cloudflare Workers / D1",
      productionUrl: "https://ai-platform-core.karukimori.workers.dev",
      previewUrl: "https://ai-platform-core-preview.illusionddt.chatgpt.site",
      description: "AI実行、プロンプト、利用量、イベント記録を共通化するAI基盤アプリ。",
    },
    {
      id: "app-platform-admin",
      name: "Platform Admin",
      repository: "https://github.com/karukimori-wq/Platform-Admin",
      service: "Cloudflare Workers / D1",
      productionUrl: "https://platform-admin.karukimori.workers.dev",
      previewUrl: "https://platform-admin-preview.illusionddt.chatgpt.site",
      description: "複数アプリの稼働状況、契約状態、接続確認を横断して見る管理アプリ。",
    },
    {
      id: "app-feedback-hub",
      name: "Feedback Hub",
      repository: "https://github.com/karukimori-wq/feedback-hub",
      service: "Cloudflare / GitHub",
      productionUrl: "",
      previewUrl: "",
      description: "ユーザーの質問、不具合、改善要望を集め、AIが開発しやすい形へ整理するアプリ。",
    },
  ],
  secrets: [
    {
      id: "secret-google-sheets",
      name: "GOOGLE_SHEETS_SPREADSHEET_ID",
      description: "Secret Manager が台帳シートを読むためのSpreadsheet ID。",
      owner: "Secret Manager",
      storage: "Vercel Environment Variables",
    },
    {
      id: "secret-apc-client",
      name: "AI_PLATFORM_CORE_CLIENT_ID",
      description: "AI Platform Core を呼び出すアプリ識別子。",
      owner: "AI Platform Core",
      storage: "Vercel or Cloudflare environment",
    },
  ],
  services: [
    { id: "service-github", name: "GitHub", description: "Repository 管理。" },
    { id: "service-vercel", name: "Vercel", description: "Next.jsアプリのホスティング先。" },
    { id: "service-google-sheets", name: "Google Sheets", description: "Secret Managerの固定5シート台帳。" },
    { id: "service-google-drive", name: "Google Drive", description: "README / 管理ファイル置き場。" },
    { id: "service-cloudflare", name: "Cloudflare", description: "Workers / D1 を使うアプリの運用先。" },
    { id: "service-supabase", name: "Supabase", description: "Postgres / Auth / Storage など。" },
    { id: "service-chatgpt-sites", name: "ChatGPT Sites", description: "プレビュー / ホスティング。" },
  ],
  relations: [
    { from: "secret-google-sheets", relation: "used_by", to: "app-secret-manager" },
    { from: "app-secret-manager", relation: "uses", to: "service-github" },
    { from: "app-secret-manager", relation: "uses", to: "service-vercel" },
    { from: "app-secret-manager", relation: "uses", to: "service-google-sheets" },
    { from: "app-secret-manager", relation: "uses", to: "service-google-drive" },
    { from: "app-external-intelligence-system", relation: "uses", to: "service-github" },
    { from: "app-external-intelligence-system", relation: "uses", to: "service-vercel" },
    { from: "app-external-intelligence-system", relation: "uses", to: "service-supabase" },
    { from: "app-growth-engine", relation: "uses", to: "service-github" },
    { from: "app-growth-engine", relation: "uses", to: "service-vercel" },
    { from: "app-growth-engine", relation: "uses", to: "service-supabase" },
    { from: "app-velvet", relation: "uses", to: "service-github" },
    { from: "app-velvet", relation: "uses", to: "service-cloudflare" },
    { from: "app-numeria-studio", relation: "uses", to: "service-github" },
    { from: "app-numeria-studio", relation: "uses", to: "service-cloudflare" },
    { from: "app-numeria-studio", relation: "uses", to: "service-chatgpt-sites" },
    { from: "app-sns-planner", relation: "uses", to: "service-github" },
    { from: "app-sns-planner", relation: "uses", to: "service-chatgpt-sites" },
    { from: "app-communication-planner", relation: "uses", to: "service-github" },
    { from: "app-communication-planner", relation: "uses", to: "service-cloudflare" },
    { from: "app-ai-platform-core", relation: "uses", to: "service-github" },
    { from: "app-ai-platform-core", relation: "uses", to: "service-cloudflare" },
    { from: "app-platform-admin", relation: "uses", to: "service-github" },
    { from: "app-platform-admin", relation: "uses", to: "service-cloudflare" },
    { from: "app-feedback-hub", relation: "uses", to: "service-github" },
    { from: "app-feedback-hub", relation: "uses", to: "service-cloudflare" },
  ],
  links: [
    {
      parentType: "app",
      parentId: "app-secret-manager",
      title: "GitHub Repository",
      url: "https://github.com/karukimori-wq/Secret-Manager",
    },
    {
      parentType: "service",
      parentId: "service-vercel",
      title: "Vercel Dashboard",
      url: "https://vercel.com/dashboard",
    },
  ],
};
